#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "---------        执行提交信息校验         ---------"

echo "--------- Verify submission information ---------"

npx --no-install commitlint --edit $1
